import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  ActivityIndicator, Alert, KeyboardAvoidingView, Modal, Platform, Pressable, SafeAreaView,
  ScrollView, StatusBar, StyleSheet, Text, TextInput, View, type TextInputProps,
} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { useSQLiteContext } from 'expo-sqlite';
import { clearBusinessLogo, exportEncryptedBackup, importEncryptedBackup, persistBusinessLogo } from './backup';
import {
  createQuote, deleteAllLocalData, finalizeQuote, finalizeReceipt, getBusinessProfile, getDocumentUsage, getQuote,
  listClients, listQuotes, recordPayment, saveBusinessProfile, saveClient, saveQuoteDraft,
  setQuoteStatus, voidPayment,
} from './database';
import {
  DEFAULT_BRAND_COLOR, type BusinessProfile, type Client, type PaymentMethod, type Quote,
  type QuoteSummary, type UsageSummary, formatFolio, money, newLinePlaceholder, parseMoneyToCents,
  paymentSummary, quoteTotal,
} from './domain';
import { shareQuotePdf, shareReceiptPdf } from './documents';
import { useSubscription } from './subscription';

type Tab = 'Inicio' | 'Clientes' | 'Ajustes';
type Screen = { name: 'tabs' } | { name: 'quote'; id: string } | { name: 'paywall' };

const C = { green: '#0E5E4A', dark: '#073B2F', mint: '#DCECE5', ink: '#17221D', muted: '#68756F', paper: '#F5F3ED', white: '#FFFFFF', amber: '#F0A33B', line: '#DFE3DE', red: '#B83A35', blue: '#326A86' };
const STATUS: Record<Quote['status'], string> = { draft: 'BORRADOR', finalized: 'LISTA', sent: 'ENVIADA', accepted: 'ACEPTADA', rejected: 'RECHAZADA' };

export function JaleApp() {
  const db = useSQLiteContext(); const subscription = useSubscription();
  const [profile, setProfile] = useState<BusinessProfile | null | undefined>(undefined);
  const [quotes, setQuotes] = useState<QuoteSummary[]>([]); const [clients, setClients] = useState<Client[]>([]);
  const [usage, setUsage] = useState<UsageSummary | null>(null); const [tab, setTab] = useState<Tab>('Inicio');
  const [screen, setScreen] = useState<Screen>({ name: 'tabs' }); const [busy, setBusy] = useState(false);

  const refresh = useCallback(async () => {
    const [nextProfile, nextQuotes, nextClients, nextUsage] = await Promise.all([getBusinessProfile(db), listQuotes(db), listClients(db), getDocumentUsage(db)]);
    setProfile(nextProfile); setQuotes(nextQuotes); setClients(nextClients); setUsage(nextUsage);
  }, [db]);
  useEffect(() => { void refresh().catch(error => Alert.alert('No se pudo abrir Jale', message(error))); }, [refresh]);

  const run = async (work: () => Promise<void>) => { setBusy(true); try { await work(); } catch (error) { Alert.alert('No se pudo completar', message(error)); } finally { setBusy(false); } };
  if (profile === undefined || subscription.loading) return <Loading />;
  if (!profile) return <Onboarding save={async form => { await saveBusinessProfile(db, form); await refresh(); }} />;
  const openNewQuote = () => void run(async () => { const id = await createQuote(db); setScreen({ name: 'quote', id }); });

  return <SafeAreaView style={s.safe}><StatusBar barStyle="dark-content" backgroundColor={C.paper} />
    {screen.name === 'quote' && <QuoteScreen id={screen.id} profile={profile} clients={clients} isPro={subscription.isPro} close={async () => { await refresh(); setScreen({ name: 'tabs' }); }} showPaywall={() => setScreen({ name: 'paywall' })} />}
    {screen.name === 'paywall' && <Paywall close={() => setScreen({ name: 'tabs' })} />}
    {screen.name === 'tabs' && <>
      <AppHeader profile={profile} isPro={subscription.isPro} usage={usage} />
      {tab === 'Inicio' && <Home quotes={quotes} usage={usage} isPro={subscription.isPro} openNew={openNewQuote} open={id => setScreen({ name: 'quote', id })} showPaywall={() => setScreen({ name: 'paywall' })} />}
      {tab === 'Clientes' && <ClientsScreen clients={clients} refresh={refresh} />}
      {tab === 'Ajustes' && <Settings profile={profile} isPro={subscription.isPro} refresh={refresh} showPaywall={() => setScreen({ name: 'paywall' })} />}
      <BottomNav tab={tab} setTab={setTab} />
    </>}
    {busy && <BusyOverlay />}
  </SafeAreaView>;
}

function Loading() { return <SafeAreaView style={[s.safe, s.center]}><ActivityIndicator color={C.green} size="large" /><Text style={s.muted}>Abriendo tu información local…</Text></SafeAreaView>; }
function BusyOverlay() { return <View style={s.busy}><ActivityIndicator color={C.white} size="large" /></View>; }
function message(error: unknown) { return error instanceof Error ? error.message : String(error); }

function Onboarding({ save }: { save: (form: Pick<BusinessProfile, 'name' | 'trade' | 'phone' | 'logoUri' | 'brandColor'>) => Promise<void> }) {
  const [name, setName] = useState(''); const [trade, setTrade] = useState(''); const [phone, setPhone] = useState(''); const [busy, setBusy] = useState(false);
  return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={C.dark} /><ScrollView contentContainerStyle={s.onboarding} keyboardShouldPersistTaps="handled">
    <View style={s.brandMark}><Text style={s.brandMarkText}>J</Text></View><Text style={s.onboardingTitle}>Tu trabajo, presentado como se merece.</Text><Text style={s.onboardingCopy}>Cotiza, cobra y comparte documentos profesionales aun cuando no tengas señal.</Text>
    <View style={s.formCard}><Field label="NOMBRE DEL NEGOCIO *" value={name} setValue={setName} placeholder="Ej. Plomería Ramírez" autoFocus /><Field label="OFICIO" value={trade} setValue={setTrade} placeholder="Plomería, albañilería, electricidad…" /><Field label="TELÉFONO" value={phone} setValue={setPhone} placeholder="Opcional" keyboardType="phone-pad" />
      <Primary disabled={busy || !name.trim()} label={busy ? 'Guardando…' : 'Comenzar'} onPress={() => { setBusy(true); void save({ name, trade, phone, logoUri: null, brandColor: DEFAULT_BRAND_COLOR }).catch(error => Alert.alert('Revisa tus datos', message(error))).finally(() => setBusy(false)); }} />
    </View><Text style={s.privacyHint}>Tus datos se guardan primero en este teléfono.</Text>
  </ScrollView></SafeAreaView>;
}

function AppHeader({ profile, isPro, usage }: { profile: BusinessProfile; isPro: boolean; usage: UsageSummary | null }) {
  return <View style={s.header}><View style={{ flex: 1 }}><Text style={s.eyebrow}>JALE · {profile.trade || 'OFICIOS'}</Text><Text style={s.headerTitle}>{profile.name}</Text></View><View style={[s.planPill, isPro && s.planPillPro]}><Text style={[s.planText, isPro && s.planTextPro]}>{isPro ? 'PRO' : `${usage?.remaining ?? 3} GRATIS`}</Text></View></View>;
}

function Home({ quotes, usage, isPro, openNew, open, showPaywall }: { quotes: QuoteSummary[]; usage: UsageSummary | null; isPro: boolean; openNew: () => void; open: (id: string) => void; showPaywall: () => void }) {
  const [query, setQuery] = useState('');
  const filtered = quotes.filter(quote => quote.clientName.toLowerCase().includes(query.toLowerCase()) || formatFolio('COT', quote.quoteNumber).includes(query.toUpperCase()));
  return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <View style={s.hero}><Text style={s.heroKicker}>COTIZA EN MENOS DE UN MINUTO</Text><Text style={s.heroTitle}>Que tu trabajo hable bien de ti.</Text><Text style={s.heroCopy}>Concepto, precio y listo para WhatsApp.</Text><Pressable style={s.heroButton} onPress={openNew}><Text style={s.heroButtonText}>＋ Nueva cotización</Text></Pressable></View>
    {!isPro && usage && <Pressable style={s.usageCard} onPress={showPaywall}><View style={{ flex: 1 }}><Text style={s.usageTitle}>{usage.used} de {usage.limit} documentos usados</Text><View style={s.progress}><View style={[s.progressOn, { width: `${Math.min(100, usage.used / usage.limit * 100)}%` }]} /></View></View><Text style={s.usageLink}>Ver Pro ›</Text></Pressable>}
    <TextInput value={query} onChangeText={setQuery} placeholder="Buscar cliente o folio" style={s.search} />
    <SectionTitle title="COTIZACIONES RECIENTES" />
    {filtered.length === 0 ? <Empty title={quotes.length ? 'Sin resultados' : 'Tu historial empieza aquí'} copy={quotes.length ? 'Prueba con otro nombre o folio.' : 'Crea tu primera cotización y siempre tendrás una copia local.'} /> : filtered.map(quote => <QuoteCard key={quote.id} quote={quote} onPress={() => open(quote.id)} />)}
  </ScrollView>;
}

function QuoteCard({ quote, onPress }: { quote: QuoteSummary; onPress: () => void }) {
  return <Pressable style={({ pressed }) => [s.card, pressed && s.pressed]} onPress={onPress}><View style={s.row}><View><Text style={s.folio}>{formatFolio('COT', quote.quoteNumber)}</Text><Text style={s.cardTitle}>{quote.clientName || 'Cliente pendiente'}</Text></View><Text style={[s.status, quote.status === 'accepted' && s.statusOk, quote.status === 'rejected' && s.statusBad]}>{STATUS[quote.status]}</Text></View><View style={s.divider} /><View style={s.row}><Text style={s.muted}>{new Date(quote.issuedAt).toLocaleDateString('es-MX')}</Text><Text style={s.amount}>{money(quote.totalCents)}</Text></View>{quote.status === 'accepted' && quote.balanceCents > 0 && <Text style={s.balance}>Saldo pendiente: {money(quote.balanceCents)}</Text>}</Pressable>;
}

function QuoteScreen({ id, profile, clients, isPro, close, showPaywall }: { id: string; profile: BusinessProfile; clients: Client[]; isPro: boolean; close: () => Promise<void>; showPaywall: () => void }) {
  const db = useSQLiteContext(); const [quote, setQuote] = useState<Quote | null>(null); const [saving, setSaving] = useState(false); const [paymentOpen, setPaymentOpen] = useState(false);
  const reload = useCallback(async () => setQuote(await getQuote(db, id)), [db, id]);
  useEffect(() => { void reload(); }, [reload]);
  useEffect(() => {
    if (!quote) return; const timer = setTimeout(() => { setSaving(true); void saveQuoteDraft(db, quote).catch(error => console.warn('No se guardó el borrador:', error)).finally(() => setSaving(false)); }, 500); return () => clearTimeout(timer);
  }, [db, quote]);
  if (!quote) return <Loading />;
  const total = quoteTotal(quote.lines); const summary = paymentSummary(total, quote.payments);
  const patch = (value: Partial<Quote>) => setQuote(current => current ? { ...current, ...value } : current);
  const updateLine = (lineId: string, field: 'concept' | 'quantity' | 'unitPriceCents', value: string) => patch({ lines: quote.lines.map(line => line.id === lineId ? { ...line, [field]: field === 'concept' ? value : field === 'quantity' ? Math.max(0, Number(value.replace(',', '.')) || 0) : parseMoneyToCents(value) } : line) });
  const gated = async (task: () => Promise<void>) => { try { await task(); } catch (error) { if (message(error) === 'FREE_LIMIT_REACHED') showPaywall(); else Alert.alert('Revisa la cotización', message(error)); } };
  const share = () => void gated(async () => { setSaving(true); try { const final = await finalizeQuote(db, { ...quote, totalCents: total }, isPro); if (!final) return; setQuote(final); await shareQuotePdf(profile, final, isPro); if (final.status === 'finalized') setQuote(await setQuoteStatus(db, final.id, 'sent')); } finally { setSaving(false); } });
  const saveAndClose = () => void gated(async () => { setSaving(true); try { await saveQuoteDraft(db, quote); await close(); } finally { setSaving(false); } });
  return <KeyboardAvoidingView style={s.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={s.editorHeader}><Pressable onPress={saveAndClose}><Text style={s.back}>‹ Historial</Text></Pressable><View style={{ alignItems: 'flex-end' }}><Text style={s.folio}>{formatFolio('COT', quote.quoteNumber)}</Text><Text style={s.saving}>{saving ? 'Guardando…' : 'Guardado localmente'}</Text></View></View>
    <ScrollView contentContainerStyle={s.editorContent} keyboardShouldPersistTaps="handled">
      <View style={s.editorIntro}><Text style={s.editorTitle}>{quote.status === 'draft' ? 'Nueva cotización' : quote.clientName}</Text><Text style={s.muted}>Los cambios se guardan automáticamente.</Text></View>
      <Field label="CLIENTE *" value={quote.clientName} setValue={clientName => patch({ clientName, clientId: clients.find(client => client.name === clientName)?.id ?? null })} placeholder="Nombre del cliente" />
      {!!clients.length && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chipRow}>{clients.slice(0, 8).map(client => <Chip key={client.id} label={client.name} selected={quote.clientId === client.id} onPress={() => patch({ clientId: client.id, clientName: client.name })} />)}</ScrollView>}
      <View style={s.row}><View style={{ flex: 1 }}><Text style={s.label}>FECHA</Text><Text style={s.staticField}>{new Date(quote.issuedAt).toLocaleDateString('es-MX')}</Text></View><View style={{ flex: 1 }}><Field label="VÁLIDA HASTA" value={quote.validUntil ?? ''} setValue={value => patch({ validUntil: value || null })} placeholder="AAAA-MM-DD" maxLength={10} /></View></View>
      <SectionTitle title="CONCEPTOS" />
      {quote.lines.map((line, index) => <View style={s.lineCard} key={line.id}><View style={s.lineNumber}><Text style={s.lineNumberText}>{index + 1}</Text></View><TextInput value={line.concept} onChangeText={value => updateLine(line.id, 'concept', value)} placeholder="Trabajo o material" style={[s.input, { flex: 1 }]} /><View style={s.lineFields}><TextInput value={line.quantity ? String(line.quantity) : ''} onChangeText={value => updateLine(line.id, 'quantity', value)} keyboardType="decimal-pad" placeholder="Cant." style={[s.input, s.qty]} /><TextInput value={line.unitPriceCents ? String(line.unitPriceCents / 100) : ''} onChangeText={value => updateLine(line.id, 'unitPriceCents', value)} keyboardType="decimal-pad" placeholder="Precio $" style={[s.input, { flex: 1 }]} /><Text style={s.lineAmount}>{money(Math.round(line.quantity * line.unitPriceCents))}</Text></View>{quote.lines.length > 1 && <Pressable onPress={() => patch({ lines: quote.lines.filter(item => item.id !== line.id) })}><Text style={s.deleteText}>Quitar concepto</Text></Pressable>}</View>)}
      <Pressable style={s.addLine} onPress={() => patch({ lines: [...quote.lines, newLinePlaceholder(quote.lines.length)] })}><Text style={s.addLineText}>＋ Agregar concepto</Text></Pressable>
      <View style={s.totalCard}><Text style={s.totalLabel}>TOTAL</Text><Text style={s.totalValue}>{money(total)}</Text></View>
      <Field label="NOTAS" value={quote.notes} setValue={notes => patch({ notes })} placeholder="Alcance, materiales o condiciones…" multiline />
      {quote.status === 'draft' ? <Primary label="Finalizar y compartir PDF" onPress={share} /> : <><Primary label="Compartir cotización" onPress={share} /><View style={s.actionRow}>{quote.status !== 'accepted' && <Secondary label="Aceptar" onPress={() => void setQuoteStatus(db, quote.id, 'accepted').then(setQuote)} />}{quote.status !== 'rejected' && <Secondary label="Rechazar" destructive onPress={() => void setQuoteStatus(db, quote.id, 'rejected').then(setQuote)} />}</View></>}
      {quote.status === 'accepted' && <View style={s.paymentSection}><SectionTitle title="PAGOS" /><View style={s.paymentSummary}><View><Text style={s.muted}>Pagado</Text><Text style={s.paymentNumber}>{money(summary.paidCents)}</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={s.muted}>Saldo</Text><Text style={[s.paymentNumber, summary.balanceCents > 0 && { color: C.amber }]}>{money(summary.balanceCents)}</Text></View></View>{quote.payments.map(payment => <View style={[s.card, payment.voidedAt && { opacity: .5 }]} key={payment.id}><View style={s.row}><View><Text style={s.folio}>{formatFolio('REC', payment.receiptNumber)}</Text><Text style={s.cardTitle}>{money(payment.amountCents)}</Text><Text style={s.muted}>{new Date(payment.paidAt).toLocaleDateString('es-MX')} · {payment.method === 'cash' ? 'Efectivo' : payment.method === 'transfer' ? 'Transferencia' : 'Otro'}</Text></View>{payment.voidedAt ? <Text style={s.statusBad}>ANULADO</Text> : <View><Pressable onPress={() => void gated(async () => { const finalPayment = await finalizeReceipt(db, payment.id, isPro); const latest = await getQuote(db, quote.id); if (latest) { setQuote(latest); await shareReceiptPdf(profile, latest, finalPayment, isPro); } })}><Text style={s.link}>Compartir recibo</Text></Pressable><Pressable onPress={() => Alert.alert('Anular pago', 'El registro se conservará para mantener trazabilidad.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Anular', style: 'destructive', onPress: () => void voidPayment(db, payment.id).then(reload) }])}><Text style={s.deleteText}>Anular</Text></Pressable></View>}</View></View>)}{summary.balanceCents > 0 && <Primary label="＋ Registrar pago" onPress={() => setPaymentOpen(true)} />}</View>}
    </ScrollView><PaymentModal visible={paymentOpen} balance={summary.balanceCents} close={() => setPaymentOpen(false)} save={async (method, cents, notes) => { await recordPayment(db, { ...quote, totalCents: total }, method, cents, notes); setPaymentOpen(false); await reload(); }} /></KeyboardAvoidingView>;
}

function PaymentModal({ visible, balance, close, save }: { visible: boolean; balance: number; close: () => void; save: (method: PaymentMethod, cents: number, notes: string) => Promise<void> }) {
  const [amount, setAmount] = useState(''); const [method, setMethod] = useState<PaymentMethod>('cash'); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (visible) setAmount(String(balance / 100)); }, [visible, balance]);
  return <Sheet visible={visible} title="Registrar pago" close={close}><Text style={s.muted}>Saldo actual: {money(balance)}</Text><Field label="IMPORTE *" value={amount} setValue={setAmount} placeholder="0.00" keyboardType="decimal-pad" autoFocus /><Text style={s.label}>FORMA DE PAGO</Text><View style={s.chipRow}><Chip label="Efectivo" selected={method === 'cash'} onPress={() => setMethod('cash')} /><Chip label="Transferencia" selected={method === 'transfer'} onPress={() => setMethod('transfer')} /><Chip label="Otro" selected={method === 'other'} onPress={() => setMethod('other')} /></View><Field label="NOTA" value={notes} setValue={setNotes} placeholder="Opcional" /><Primary disabled={busy} label={busy ? 'Guardando…' : 'Guardar pago'} onPress={() => { setBusy(true); void save(method, parseMoneyToCents(amount), notes).catch(error => Alert.alert('No se guardó', message(error))).finally(() => setBusy(false)); }} /></Sheet>;
}

function ClientsScreen({ clients, refresh }: { clients: Client[]; refresh: () => Promise<void> }) {
  const db = useSQLiteContext(); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Client | null | undefined>(undefined);
  const filtered = clients.filter(client => `${client.name} ${client.phone} ${client.address}`.toLowerCase().includes(query.toLowerCase()));
  return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.row}><TextInput value={query} onChangeText={setQuery} placeholder="Buscar cliente" style={[s.search, { flex: 1 }]} /><Pressable style={s.squareButton} onPress={() => setEditing(null)}><Text style={s.squareButtonText}>＋</Text></Pressable></View><SectionTitle title={`${clients.length} CLIENTES`} />{filtered.length ? filtered.map(client => <Pressable key={client.id} style={s.card} onPress={() => setEditing(client)}><Text style={s.cardTitle}>{client.name}</Text><Text style={s.muted}>{client.phone || 'Sin teléfono'}{client.address ? ` · ${client.address}` : ''}</Text></Pressable>) : <Empty title="Sin clientes" copy="Los clientes de tus cotizaciones aparecerán aquí." />}<ClientModal client={editing} visible={editing !== undefined} close={() => setEditing(undefined)} save={async form => { await saveClient(db, { ...editing, ...form }); setEditing(undefined); await refresh(); }} /></ScrollView>;
}

function ClientModal({ client, visible, close, save }: { client: Client | null | undefined; visible: boolean; close: () => void; save: (form: { name: string; phone: string; address: string; notes: string }) => Promise<void> }) {
  const [form, setForm] = useState({ name: '', phone: '', address: '', notes: '' });
  useEffect(() => { if (visible) setForm({ name: client?.name ?? '', phone: client?.phone ?? '', address: client?.address ?? '', notes: client?.notes ?? '' }); }, [visible, client]);
  const field = (key: keyof typeof form, label: string, placeholder: string) => <Field label={label} value={form[key]} setValue={value => setForm(current => ({ ...current, [key]: value }))} placeholder={placeholder} />;
  return <Sheet visible={visible} title={client ? 'Editar cliente' : 'Nuevo cliente'} close={close}>{field('name', 'NOMBRE *', 'Nombre')}{field('phone', 'TELÉFONO', 'Opcional')}{field('address', 'DIRECCIÓN', 'Opcional')}{field('notes', 'NOTAS', 'Referencias u observaciones')}<Primary label="Guardar cliente" onPress={() => void save(form).catch(error => Alert.alert('No se guardó', message(error)))} /></Sheet>;
}

function Settings({ profile, isPro, refresh, showPaywall }: { profile: BusinessProfile; isPro: boolean; refresh: () => Promise<void>; showPaywall: () => void }) {
  const db = useSQLiteContext(); const subscription = useSubscription(); const [editing, setEditing] = useState(false); const [backupMode, setBackupMode] = useState<'export' | 'import' | null>(null);
  const deleteData = () => Alert.alert('Borrar datos locales', 'Se eliminarán el negocio, clientes, cotizaciones y pagos de este teléfono. Esta acción no se puede deshacer.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Borrar todo', style: 'destructive', onPress: () => void deleteAllLocalData(db).then(clearBusinessLogo).then(refresh).catch(error => Alert.alert('No se pudo borrar', message(error))) }]);
  return <ScrollView contentContainerStyle={s.content}><SectionTitle title="TU NEGOCIO" /><View style={s.card}><Text style={s.cardTitle}>{profile.name}</Text><Text style={s.muted}>{profile.trade || 'Oficio sin especificar'} · {profile.phone || 'Sin teléfono'}</Text><Pressable onPress={() => setEditing(true)}><Text style={s.link}>Editar identidad</Text></Pressable></View><SectionTitle title="SUSCRIPCIÓN" /><Pressable style={s.card} onPress={isPro ? () => void subscription.manage() : showPaywall}><View style={s.row}><View><Text style={s.cardTitle}>{isPro ? 'Jale Pro' : 'Plan Gratis'}</Text><Text style={s.muted}>{isPro ? 'Documentos ilimitados y personalización' : 'Hasta 3 documentos al mes'}</Text></View><Text style={s.link}>{isPro ? 'Administrar' : 'Mejorar ›'}</Text></View></Pressable><SectionTitle title="RESPALDO" /><View style={s.card}><Text style={s.cardTitle}>Tus datos siguen siendo tuyos</Text><Text style={s.muted}>Android hace una copia automática cuando es posible. Para mayor seguridad, guarda también un archivo cifrado.</Text><Secondary label="Exportar respaldo cifrado" onPress={() => setBackupMode('export')} /><Secondary label="Importar respaldo" onPress={() => setBackupMode('import')} /></View><SectionTitle title="PRIVACIDAD" /><View style={s.card}><Text style={s.cardTitle}>Funciona sin cuenta</Text><Text style={s.muted}>Clientes, cotizaciones y pagos se guardan en este teléfono. Jale no procesa pagos ni genera comprobantes fiscales.</Text><Secondary label="Borrar todos los datos locales" destructive onPress={deleteData} /></View><Text style={s.version}>Jale 1.0.0 · Android</Text><ProfileModal profile={profile} isPro={isPro} visible={editing} close={() => setEditing(false)} showPaywall={showPaywall} save={async form => { await saveBusinessProfile(db, form); setEditing(false); await refresh(); }} /><BackupPasswordModal mode={backupMode} close={() => setBackupMode(null)} run={async password => { if (backupMode === 'export') await exportEncryptedBackup(db, password); else { const restored = await importEncryptedBackup(db, password); if (restored) await refresh(); } }} /></ScrollView>;
}

function ProfileModal({ profile, isPro, visible, close, showPaywall, save }: { profile: BusinessProfile; isPro: boolean; visible: boolean; close: () => void; showPaywall: () => void; save: (form: Pick<BusinessProfile, 'name' | 'trade' | 'phone' | 'logoUri' | 'brandColor'>) => Promise<void> }) {
  const [form, setForm] = useState({ name: profile.name, trade: profile.trade, phone: profile.phone, logoUri: profile.logoUri, brandColor: profile.brandColor });
  useEffect(() => { if (visible) setForm({ name: profile.name, trade: profile.trade, phone: profile.phone, logoUri: profile.logoUri, brandColor: profile.brandColor }); }, [visible, profile]);
  const pickLogo = async () => { if (!isPro) return showPaywall(); const result = await DocumentPicker.getDocumentAsync({ type: ['image/png', 'image/jpeg'], copyToCacheDirectory: true }); const asset = result.canceled ? undefined : result.assets[0]; if (asset) { const logoUri = await persistBusinessLogo(asset.uri); setForm(current => ({ ...current, logoUri })); } };
  return <Sheet visible={visible} title="Identidad del negocio" close={close}><Field label="NOMBRE *" value={form.name} setValue={name => setForm(current => ({ ...current, name }))} placeholder="Nombre del negocio" /><Field label="OFICIO" value={form.trade} setValue={trade => setForm(current => ({ ...current, trade }))} placeholder="Tu especialidad" /><Field label="TELÉFONO" value={form.phone} setValue={phone => setForm(current => ({ ...current, phone }))} placeholder="Opcional" keyboardType="phone-pad" /><Pressable style={s.upload} onPress={() => void pickLogo()}><Text style={s.uploadText}>{form.logoUri ? '✓ Logo seleccionado' : isPro ? '＋ Agregar logo' : 'Logo · Función Pro'}</Text></Pressable><Text style={s.label}>COLOR INSTITUCIONAL</Text><View style={s.colorRow}>{['#0E5E4A', '#215A8E', '#8A422A', '#5F477C', '#20272B'].map(color => <Pressable key={color} disabled={!isPro} onPress={() => setForm(current => ({ ...current, brandColor: color }))} style={[s.color, { backgroundColor: color }, form.brandColor === color && s.colorSelected, !isPro && { opacity: .35 }]} />)}</View><Primary label="Guardar cambios" onPress={() => void save(form).catch(error => Alert.alert('No se guardó', message(error)))} /></Sheet>;
}

function BackupPasswordModal({ mode, close, run }: { mode: 'export' | 'import' | null; close: () => void; run: (password: string) => Promise<void> }) {
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (mode) { setPassword(''); setConfirm(''); } }, [mode]);
  return <Sheet visible={mode !== null} title={mode === 'export' ? 'Proteger respaldo' : 'Abrir respaldo'} close={close}><Text style={s.muted}>{mode === 'export' ? 'Usa una contraseña de al menos 8 caracteres. Jale no puede recuperarla.' : 'Escribe la contraseña con la que se creó el respaldo.'}</Text><Field label="CONTRASEÑA" value={password} setValue={setPassword} placeholder="Mínimo 8 caracteres" secureTextEntry autoFocus />{mode === 'export' && <Field label="CONFIRMAR" value={confirm} setValue={setConfirm} placeholder="Repite la contraseña" secureTextEntry />}<Primary disabled={busy || password.length < 8 || (mode === 'export' && password !== confirm)} label={busy ? 'Procesando…' : mode === 'export' ? 'Crear y compartir' : 'Elegir archivo e importar'} onPress={() => { setBusy(true); void run(password).then(close).catch(error => Alert.alert('No se pudo procesar', message(error))).finally(() => setBusy(false)); }} /></Sheet>;
}

function Paywall({ close }: { close: () => void }) {
  const subscription = useSubscription(); const [busy, setBusy] = useState(false);
  const offer = (id: 'monthly' | 'yearly') => subscription.offers.find(item => item.basePlanIdAndroid === id);
  const buy = (id: 'monthly' | 'yearly') => { setBusy(true); void subscription.buy(id).catch(error => Alert.alert('Compra no disponible', message(error))).finally(() => setBusy(false)); };
  return <ScrollView contentContainerStyle={s.paywall}><Pressable onPress={close} style={s.paywallClose}><Text style={s.back}>‹ Volver</Text></Pressable><View style={s.proBadge}><Text style={s.proBadgeText}>JALE PRO</Text></View><Text style={s.paywallTitle}>Tu imagen profesional, sin límites.</Text><Text style={s.paywallCopy}>Crea todos los documentos que necesites y personalízalos con la identidad de tu negocio.</Text>{['Cotizaciones y recibos ilimitados', 'Logo y color institucional', 'Documentos sin marca de Jale', '100 capturas de voz al mes cuando llegue IA', 'Tus datos permanecen locales'].map(item => <View key={item} style={s.benefit}><Text style={s.benefitCheck}>✓</Text><Text style={s.benefitText}>{item}</Text></View>)}<Pressable disabled={busy || !offer('yearly')} style={[s.planCard, s.planCardBest]} onPress={() => buy('yearly')}><Text style={s.best}>MEJOR VALOR</Text><Text style={s.planName}>Anual</Text><Text style={s.planPrice}>{offer('yearly')?.displayPrice ?? '$799 MXN'} <Text style={s.planPeriod}>/ año</Text></Text></Pressable><Pressable disabled={busy || !offer('monthly')} style={s.planCard} onPress={() => buy('monthly')}><Text style={s.planName}>Mensual</Text><Text style={s.planPrice}>{offer('monthly')?.displayPrice ?? '$89 MXN'} <Text style={s.planPeriod}>/ mes</Text></Text></Pressable>{!subscription.connected && <Text style={s.warning}>Conéctate a internet e instala la app desde la pista de Google Play para comprar.</Text>}<Pressable onPress={() => void subscription.restore().then(active => Alert.alert(active ? 'Compra restaurada' : 'Sin compra activa', active ? 'Jale Pro está activo.' : 'Google Play no encontró una suscripción activa.')).catch(error => Alert.alert('No se pudo restaurar', message(error)))}><Text style={s.restore}>Restaurar compra</Text></Pressable><Text style={s.paywallLegal}>La suscripción se renueva automáticamente y puede administrarse desde Google Play. Tus datos existentes nunca se eliminan al cancelar.</Text></ScrollView>;
}

function BottomNav({ tab, setTab }: { tab: Tab; setTab: (tab: Tab) => void }) { return <View style={s.nav}>{(['Inicio', 'Clientes', 'Ajustes'] as Tab[]).map(item => <Pressable key={item} style={s.navItem} onPress={() => setTab(item)}><Text style={s.navIcon}>{item === 'Inicio' ? '▤' : item === 'Clientes' ? '●●' : '⚙'}</Text><Text style={[s.navText, tab === item && s.navActive]}>{item}</Text></Pressable>)}</View>; }
function Field({ label, value, setValue, multiline, ...props }: { label: string; value: string; setValue: (value: string) => void } & Omit<TextInputProps, 'value' | 'onChangeText'>) { return <View style={{ flex: 1 }}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={setValue} placeholderTextColor="#9AA39F" multiline={multiline} style={[s.input, multiline && { minHeight: 82, textAlignVertical: 'top' }]} {...props} /></View>; }
function Primary({ label, onPress, disabled }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable disabled={disabled} style={({ pressed }) => [s.primary, (pressed || disabled) && { opacity: .65 }]} onPress={onPress}><Text style={s.primaryText}>{label}</Text></Pressable>; }
function Secondary({ label, onPress, destructive }: { label: string; onPress: () => void; destructive?: boolean }) { return <Pressable style={({ pressed }) => [s.secondary, destructive && { borderColor: '#E5B7B3' }, pressed && s.pressed]} onPress={onPress}><Text style={[s.secondaryText, destructive && { color: C.red }]}>{label}</Text></Pressable>; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable style={[s.chip, selected && s.chipOn]} onPress={onPress}><Text style={[s.chipText, selected && s.chipTextOn]}>{label}</Text></Pressable>; }
function SectionTitle({ title }: { title: string }) { return <Text style={s.sectionTitle}>{title}</Text>; }
function Empty({ title, copy }: { title: string; copy: string }) { return <View style={s.empty}><Text style={s.emptyTitle}>{title}</Text><Text style={s.muted}>{copy}</Text></View>; }
function Sheet({ visible, title, close, children }: { visible: boolean; title: string; close: () => void; children: React.ReactNode }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={close}><KeyboardAvoidingView style={s.backdrop} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView style={s.sheet} contentContainerStyle={s.sheetContent} keyboardShouldPersistTaps="handled"><View style={s.sheetHandle} /><Text style={s.sheetTitle}>{title}</Text>{children}<Pressable onPress={close}><Text style={s.cancel}>Cancelar</Text></Pressable></ScrollView></KeyboardAvoidingView></Modal>; }

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.paper }, center: { alignItems: 'center', justifyContent: 'center', gap: 12 }, muted: { color: C.muted, lineHeight: 20 }, busy: { ...StyleSheet.absoluteFill, backgroundColor: '#0007', alignItems: 'center', justifyContent: 'center', zIndex: 50 },
  onboarding: { flexGrow: 1, backgroundColor: C.dark, padding: 24, paddingTop: 54, gap: 16 }, brandMark: { width: 54, height: 54, borderRadius: 17, backgroundColor: C.amber, alignItems: 'center', justifyContent: 'center' }, brandMarkText: { fontSize: 30, color: C.dark, fontWeight: '900' }, onboardingTitle: { fontSize: 34, lineHeight: 38, fontWeight: '900', color: C.white, marginTop: 15 }, onboardingCopy: { color: '#CDE0D8', fontSize: 17, lineHeight: 24 }, formCard: { backgroundColor: C.paper, borderRadius: 24, padding: 18, gap: 12, marginTop: 10 }, privacyHint: { color: '#AFC7BD', textAlign: 'center', fontSize: 12 },
  header: { paddingHorizontal: 18, paddingTop: 14, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, eyebrow: { color: C.green, fontSize: 10, letterSpacing: 1.2, fontWeight: '900' }, headerTitle: { color: C.ink, fontSize: 23, fontWeight: '900' }, planPill: { paddingVertical: 7, paddingHorizontal: 10, borderRadius: 20, backgroundColor: '#EEE8DD' }, planPillPro: { backgroundColor: C.dark }, planText: { color: C.muted, fontSize: 10, fontWeight: '900' }, planTextPro: { color: C.white },
  content: { padding: 16, paddingBottom: 105, gap: 12 }, hero: { backgroundColor: C.dark, padding: 22, borderRadius: 24, gap: 10, overflow: 'hidden' }, heroKicker: { color: C.amber, fontSize: 10, letterSpacing: 1.2, fontWeight: '900' }, heroTitle: { color: C.white, fontSize: 27, lineHeight: 31, fontWeight: '900', maxWidth: 290 }, heroCopy: { color: '#CDE0D8', fontSize: 15 }, heroButton: { marginTop: 8, backgroundColor: C.amber, borderRadius: 14, padding: 15, alignItems: 'center' }, heroButtonText: { color: C.dark, fontWeight: '900', fontSize: 16 }, usageCard: { backgroundColor: '#FFF8EB', borderColor: '#F1D29A', borderWidth: 1, padding: 14, borderRadius: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, usageTitle: { color: C.ink, fontSize: 12, fontWeight: '800' }, usageLink: { color: C.green, fontWeight: '900', fontSize: 12 }, progress: { height: 5, backgroundColor: '#EDE5D7', borderRadius: 4, marginTop: 7, overflow: 'hidden' }, progressOn: { height: '100%', backgroundColor: C.amber },
  search: { backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 13, color: C.ink }, sectionTitle: { color: C.muted, fontSize: 10, letterSpacing: 1.1, fontWeight: '900', marginTop: 7 }, card: { backgroundColor: C.white, borderWidth: 1, borderColor: C.line, padding: 15, borderRadius: 17, gap: 7 }, pressed: { opacity: .7 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 }, divider: { height: 1, backgroundColor: '#EEF0ED' }, folio: { color: C.green, fontSize: 10, letterSpacing: .7, fontWeight: '900' }, cardTitle: { color: C.ink, fontSize: 17, fontWeight: '800' }, status: { color: C.blue, fontSize: 9, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, backgroundColor: '#E4F0F4', fontWeight: '900' }, statusOk: { color: C.green, backgroundColor: C.mint }, statusBad: { color: C.red, backgroundColor: '#F8E6E4', fontSize: 9, padding: 5, borderRadius: 8, fontWeight: '900' }, amount: { color: C.ink, fontSize: 17, fontWeight: '900' }, balance: { color: '#9C641C', fontSize: 12, fontWeight: '800' }, empty: { borderWidth: 1, borderStyle: 'dashed', borderColor: '#C8CFCA', borderRadius: 18, padding: 25, gap: 5, alignItems: 'center' }, emptyTitle: { color: C.ink, fontSize: 17, fontWeight: '900' },
  nav: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', backgroundColor: C.white, borderTopWidth: 1, borderTopColor: C.line, paddingBottom: 12, paddingTop: 6 }, navItem: { flex: 1, alignItems: 'center', padding: 8, gap: 2 }, navIcon: { color: C.muted, fontSize: 16 }, navText: { color: C.muted, fontSize: 10, fontWeight: '800' }, navActive: { color: C.green },
  editorHeader: { padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: C.line }, back: { color: C.green, fontWeight: '900', paddingVertical: 6 }, saving: { color: C.muted, fontSize: 9 }, editorContent: { padding: 16, paddingBottom: 50, gap: 13 }, editorIntro: { marginBottom: 3 }, editorTitle: { color: C.ink, fontSize: 27, fontWeight: '900' }, label: { color: C.muted, fontSize: 9, letterSpacing: .9, fontWeight: '900', marginBottom: 6, marginTop: 3 }, input: { backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 12, padding: 12, color: C.ink, fontSize: 15 }, staticField: { backgroundColor: '#ECEDE9', borderRadius: 12, padding: 13, color: C.muted }, chipRow: { gap: 7, paddingVertical: 2 }, chip: { borderWidth: 1, borderColor: C.line, backgroundColor: C.white, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 9 }, chipOn: { backgroundColor: C.mint, borderColor: C.green }, chipText: { color: C.muted, fontSize: 12, fontWeight: '700' }, chipTextOn: { color: C.dark, fontWeight: '900' },
  lineCard: { backgroundColor: C.white, borderWidth: 1, borderColor: C.line, borderRadius: 17, padding: 12, gap: 9 }, lineNumber: { position: 'absolute', left: -7, top: -7, backgroundColor: C.dark, width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', zIndex: 2 }, lineNumberText: { color: C.white, fontSize: 10, fontWeight: '900' }, lineFields: { flexDirection: 'row', alignItems: 'center', gap: 8 }, qty: { width: 66 }, lineAmount: { width: 85, textAlign: 'right', color: C.ink, fontWeight: '900' }, deleteText: { color: C.red, fontSize: 11, fontWeight: '800', paddingVertical: 5, textAlign: 'right' }, addLine: { borderWidth: 1, borderStyle: 'dashed', borderColor: C.green, padding: 13, borderRadius: 13, alignItems: 'center' }, addLineText: { color: C.green, fontWeight: '900' }, totalCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: C.dark, borderRadius: 17, padding: 17 }, totalLabel: { color: '#BFD6CC', fontSize: 11, fontWeight: '900' }, totalValue: { color: C.white, fontSize: 24, fontWeight: '900' }, primary: { backgroundColor: C.green, padding: 15, borderRadius: 13, alignItems: 'center', marginTop: 3 }, primaryText: { color: C.white, fontSize: 15, fontWeight: '900' }, secondary: { borderWidth: 1, borderColor: C.green, padding: 12, borderRadius: 12, alignItems: 'center', flex: 1 }, secondaryText: { color: C.green, fontWeight: '900' }, actionRow: { flexDirection: 'row', gap: 9 },
  paymentSection: { marginTop: 12, gap: 10 }, paymentSummary: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: C.mint, borderRadius: 17, padding: 16 }, paymentNumber: { color: C.dark, fontSize: 21, fontWeight: '900' }, link: { color: C.green, fontWeight: '900', paddingVertical: 5 }, squareButton: { backgroundColor: C.green, width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, squareButtonText: { color: C.white, fontSize: 24, fontWeight: '700' },
  upload: { borderWidth: 1, borderStyle: 'dashed', borderColor: C.green, borderRadius: 13, padding: 14, alignItems: 'center' }, uploadText: { color: C.green, fontWeight: '900' }, colorRow: { flexDirection: 'row', gap: 12 }, color: { width: 36, height: 36, borderRadius: 18 }, colorSelected: { borderWidth: 4, borderColor: C.amber }, version: { color: C.muted, textAlign: 'center', fontSize: 11, padding: 20 },
  backdrop: { flex: 1, backgroundColor: '#0008', justifyContent: 'flex-end' }, sheet: { maxHeight: '91%', backgroundColor: C.paper, borderTopLeftRadius: 27, borderTopRightRadius: 27 }, sheetContent: { padding: 20, paddingBottom: 34, gap: 11 }, sheetHandle: { width: 42, height: 4, borderRadius: 2, backgroundColor: '#C8CCC8', alignSelf: 'center' }, sheetTitle: { color: C.ink, fontSize: 23, fontWeight: '900', textAlign: 'center', marginBottom: 5 }, cancel: { color: C.muted, textAlign: 'center', padding: 12, fontWeight: '800' },
  paywall: { flexGrow: 1, backgroundColor: C.dark, padding: 22, paddingBottom: 45, gap: 12 }, paywallClose: { alignSelf: 'flex-start' }, proBadge: { backgroundColor: C.amber, alignSelf: 'flex-start', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7, marginTop: 15 }, proBadgeText: { color: C.dark, fontWeight: '900', fontSize: 11 }, paywallTitle: { color: C.white, fontSize: 32, lineHeight: 37, fontWeight: '900' }, paywallCopy: { color: '#CDE0D8', fontSize: 16, lineHeight: 23, marginBottom: 5 }, benefit: { flexDirection: 'row', gap: 10, alignItems: 'center' }, benefitCheck: { color: C.amber, fontSize: 17, fontWeight: '900' }, benefitText: { color: C.white, fontWeight: '700' }, planCard: { backgroundColor: C.white, borderRadius: 17, padding: 17, marginTop: 3 }, planCardBest: { borderWidth: 3, borderColor: C.amber }, best: { color: C.green, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, planName: { color: C.ink, fontWeight: '900', fontSize: 16 }, planPrice: { color: C.dark, fontWeight: '900', fontSize: 25 }, planPeriod: { fontSize: 12, color: C.muted }, warning: { color: '#FFDDA7', lineHeight: 18, textAlign: 'center', marginTop: 4 }, restore: { color: C.amber, textAlign: 'center', fontWeight: '900', padding: 10 }, paywallLegal: { color: '#AFC7BD', textAlign: 'center', fontSize: 10, lineHeight: 15 },
});
